language: nodejs
node_js:
  - "8"

cache:
  directories:
    - node_modules

before_script:
  - npm run setup
  - npm run build

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: dist/
    github_token: $GITHUB_TOKEN
    on:
      tags: true

